
package Canvas;

import Constants.ImageConstants;
import java.awt.Color;
import java.awt.Graphics;

/*
 * BottomPanel.java
 *
 * Created on April 26, 2009, 12:10 AM
 */

/**
 *
 * @author  John
 */
public class BottomPanel extends javax.swing.JPanel implements Runnable {
    
    private boolean[] lives;
    
    private String time, score;
    
    private Thread application;

    /** Creates new form BottomPanel */
    public BottomPanel() {
        initComponents();
        
        application = null;
        
        time = "5:00";
        score = "0";
        
        lives = new boolean[4];
        
        for (int i = 0;i < 4;i++)
        {
            lives[i] = true;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 6));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        
        g.setFont(new java.awt.Font("OCR A Extended", 1, 18));
        g.setColor(Color.WHITE);
        g.drawString("Lives:", 18, 40);
        g.drawString("Time:", 312, 40);
        
        g.setFont(new java.awt.Font("OCR A Extended", 1, 24));
        g.setColor(Color.YELLOW);
        g.drawString(time, 384, 40);
        
        g.setFont(new java.awt.Font("OCR A Extended", 1, 18));
        g.setColor(Color.WHITE);
        g.drawString("Score:", 504, 40);
        
        g.setFont(new java.awt.Font("OCR A Extended", 1, 24));
        g.setColor(Color.RED);
        g.drawString(score, 584, 40);
        
        for (int i = 0;i < 4;i++)
        {
            if (lives[i] == true)
            {
                g.drawImage(new ImageConstants().frogstillup, 96 + (i*48), 9, this);
            }
        }
    }
    
    public void start()
    {
        if (application == null)
        {
            application = new Thread();
            application.start();
        }
    }
    
    @Override
    public void run()
    {
        while (true)
        {
            repaint();
        }
    }
    
    public void setTime(String Time)
    {
        time = Time;
    }
    
    public void setScore(String Score)
    {
        score = Score;
    }
    
    public void resetLives()
    {
        for (int i = 0;i < 4;i++)
        {
            lives[i] = true;
        }
    }
    
    public void lifeLost()
    {
        boolean more = true;
        
        for (int i = 3;i >= 0 && more;i--)
        {
            if (lives[i] == true)
            {
                lives[i] = false;
                
                more = false;
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
